"""Init SQLite

Revision ID: 82f9c7cd6181
Revises: 
Create Date: 2026-03-25 10:41:48.046760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f9c7cd6181'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_score', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Integer(), nullable=False),
    sa.Column('convergence_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_signals_ticker'), 'market_signals', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('historical_precedents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('outcome_10d_pct', sa.String(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['market_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_ticker'), 'portfolios', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_ticker'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_table('historical_precedents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_signals_ticker'), table_name='market_signals')
    op.drop_table('market_signals')
    # ### end Alembic commands ###
